version: 2
updates:
  # Update GitHub Actions weekly
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "pavankommi"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Update npm dependencies weekly
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "pavankommi"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

    # Group updates to reduce PR noise
    groups:
      # Group all TypeScript-related dependencies
      typescript:
        patterns:
          - "typescript"
          - "@types/*"
          - "ts-*"

      # Group all ESLint-related dependencies
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"

      # Group Jest testing dependencies
      jest:
        patterns:
          - "jest*"
          - "@types/jest"
          - "@testing-library/*"

      # Group React Native dependencies
      react-native:
        patterns:
          - "react-native*"
          - "@react-native*"

      # Group development tooling
      dev-tools:
        patterns:
          - "prettier"
          - "@evilmartians/lefthook"
          - "del-cli"
          - "commitlint"
          - "@commitlint/*"
          - "@release-it/*"

    # Ignore specific packages that need manual review
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-native"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-native-builder-bob"
        update-types: ["version-update:semver-major"]

    # Auto-merge patch and minor updates for dev dependencies
    pull-request-branch-name:
      separator: "/"
